version: '3.1'
services:
  png-server:
    image: png-server
    container_name: png-server
    build: .
    ports:
      - "19527:19527"
    command: uvicorn app:app --host 0.0.0.0 --port 19527
    tty: true
