version: '3.8'
services:
  png-server:
    image: png-server
    container_name: png-server
    build: .
    ports:
      - "19527:19527"
    command: to-pic
    volumes:
      - /etc/localtime:/etc/localtime:ro
    tty: true
